### ISSUE TITLE
模拟回测 exchange.GetRecords(1）并不会返回每秒的k线 数据 ,分辨率 最多每分钟 4条

### ISSUE THREAD

**Issue by QGB** [fmzquant/backtest_python#14]
1
![image](https://user-images.githubusercontent.com/8005654/215839545-f6c8ff64-264a-49b0-b3bc-0a9edeb93c42.png)

10 
![image](https://user-images.githubusercontent.com/8005654/215839110-197b61a2-5e19-4e87-80f9-2ea2693803e3.png)

15
![image](https://user-images.githubusercontent.com/8005654/215839900-e0edff76-15a0-4633-9ac6-ae50b1d6f91b.png)

16
![image](https://user-images.githubusercontent.com/8005654/215840165-8fd8dc9b-62e5-4bb3-a0b8-0f1cca0a9e32.png)

回测中不能用 AttributeError: 'Oo0OoO00oOO0o' object has no attribute 'GetRawJSON'

**Comment by QGB** [comment]
`exchange.GetRecords(60*60*24*30)` #周期一个月 只返回一条
 
![image](https://user-images.githubusercontent.com/8005654/215847993-d3f986eb-9241-4c4f-8bd5-1111565e63ba.png)

![image](https://user-images.githubusercontent.com/8005654/215848028-cba5442f-1dca-414b-b7e1-982267fb044b.png)

**Comment by QGB** [comment]
```
exchange.GetRecords(15) # 1s 一分钟4
exchange.GetRecords(60)
exchange.GetRecords(3*60)
exchange.GetRecords(5*60)
exchange.GetRecords(15*60)#5
exchange.GetRecords(30*60)
exchange.GetRecords(60*60)
exchange.GetRecords(60*60*2)
exchange.GetRecords(60*60*4)
exchange.GetRecords(60*60*6) #10
exchange.GetRecords(60*60*8)
exchange.GetRecords(60*60*12)
exchange.GetRecords(60*60*24)
exchange.GetRecords(60*60*24*3)
exchange.GetRecords(60*60*24*7) #15
exchange.GetRecords(60*60*24*30)
```

**Comment by fmzquant** [comment]
都是靠低层K线周期合成的，刚启动时获取的长度有限，这个长度会增加随着低层K线周期生成tick数据的在时间轴上的模拟，月级的时间长是因为低层的K线周期取的开始数据短造成的

参考下这个文章 https://www.fmz.com/bbs-topic/662
