### ISSUE TITLE
undefined name 's'

### ISSUE THREAD

**Issue by femtotrader** [fmzquant/backtest_python#8]
https://github.com/fmzquant/backtest_python/blob/23b3b8e66a12a6a7a5fed548ade5507802c9c3e2/fmz.py#L1335

[flake8](http://flake8.pycqa.org/en/latest/) can help

    fmz.py:1335:19: F821 undefined name 's'

**Comment by fmzquant** [comment]
https://github.com/fmzquant/backtest_python/commit/062da6f0e1cf15eec0b6bb22ca64717d3184d79f

**Comment by femtotrader** [comment]
oh yes flake8 didn't catch that s was in globals.
